### ISSUE TITLE
Insufficient privileges

### ISSUE THREAD

**Issue by rajeshskylux** [InteractiveIntelligence/RecordingExportExample#1]
Hi,

  Myself Rajesh here we have downloaded the zip file of RecordingExportExample and passed all parameter like credential for CIC and DB. we are getting error on below line of code

 // Download primary media
                    DownloadFile(
                        rm.GetExportUri(record["RecordingId"].ToString(), RecordingMediaType.PrimaryMedia, "", 0),
                        Path.Combine(ExportDirectory, filename));

Error message is: Insufficient privileges: User \* does not have sufficient privileges for object *

we have given full rights to the user but still getting the same error can you clarify which license and privileges is required for the same thanks in advance.

**Comment by KevinGlinski** [comment]
do you have a full stack trace of the error?

**Comment by rajeshskylux** [comment]
Hi,
   Sorry I did not get what you mean to say.

**Comment by KevinGlinski** [comment]
can you provide more context on the error?

**Comment by rajeshskylux** [comment]
StackTrace = "   at ININ.IceLib.QualityManagement.RecordingsManager.GetExportUriImpl(String recordingId, RecordingMediaType mediaType, String screenRecordingParticipantId, Int32 attachmentId) in d:\eic_clay_su03\products\eic\src\icelib\QualityManagement\RecordingsManager.cs:line 889\r\n   at ININ.IceLib.QualityManagement.RecordingsManager.GetExportUri(String recordingId, RecordingMediaType mediaType, String screenRecordingParticipantId, Int32 attachmentId) in d:\eic_clay_su03\products\eic\src\icelib\QualityManagement\RecordingsManager.cs:line 852\r\n   at ININ.Alliances.RecordingExportExample.ViewModel.ExportViewModel.ExportWorkerOnDoWork(Object sender, DoWorkEventArgs e) in C:\Users\TEMP.SKYLUXBANG\Desktop\RecordingExportExample-master\src\RecordingExportExample\RecordingExportExample\ViewModel\ExportViewModel.cs:line 336"

TargetSite = {ININ.IceLib.QualityManagement.RecordingUriData GetExportUriImpl(System.String, ININ.IceLib.QualityManagement.RecordingMediaType, System.String, Int32)}

**Comment by rajeshskylux** [comment]
Please let me know if require something more.

**Comment by rajeshskylux** [comment]
Hi Kevin,
    Please help me on the same I am waiting for your reply.

**Comment by KevinGlinski** [comment]
I'm not sure, I haven't been able to find out why it would fail.  If you need immediate help, you'll have to open a support case.

**Comment by rajeshskylux** [comment]
Hi Kevin,
  I did some RND and previous error got resolved now its coming new error.

{ININ.IceLib.IceLibException: Interaction Recorder system error.  Please contact your Interaction Recorder administrator 
   at ININ.IceLib.QualityManagement.RecordingsManager.GetExportUriImpl(String recordingId, RecordingMediaType mediaType, String screenRecordingParticipantId, Int32 attachmentId) in d:\eic_clay_su03\products\eic\src\icelib\QualityManagement\RecordingsManager.cs:line 889
   at ININ.IceLib.QualityManagement.RecordingsManager.GetExportUri(String recordingId, RecordingMediaType mediaType, String screenRecordingParticipantId, Int32 attachmentId) in d:\eic_clay_su03\products\eic\src\icelib\QualityManagement\RecordingsManager.cs:line 852
   at ININ.Alliances.RecordingExportExample.ViewModel.ExportViewModel.ExportWorkerOnDoWork(Object sender, DoWorkEventArgs e) in C:\Users\TEMP.SKYLUXBANG\Desktop\RecordingExportExample-master\src\RecordingExportExample\RecordingExportExample\ViewModel\ExportViewModel.cs:line 337}

**Comment by PrinceNebulon** [comment]
This should be addressed via a Support ticket as there is likely a configuration issue with your CIC server. Support can walk you through troubleshooting the problem.

**Comment by rajeshskylux** [comment]
Hi Kevin,
  If you find any solution on below error please help again I am getting the same error.

StackTrace = " at ININ.IceLib.QualityManagement.RecordingsManager.GetExportUriImpl(String recordingId, RecordingMediaType mediaType, String screenRecordingParticipantId, Int32 attachmentId) in d:\eic_clay_su03\products\eic\src\icelib\QualityManagement\RecordingsManager.cs:line 889\r\n at ININ.IceLib.QualityManagement.RecordingsManager.GetExportUri(String recordingId, RecordingMediaType mediaType, String screenRecordingParticipantId, Int32 attachmentId) in d:\eic_clay_su03\products\eic\src\icelib\QualityManagement\RecordingsManager.cs:line 852\r\n at ININ.Alliances.RecordingExportExample.ViewModel.ExportViewModel.ExportWorkerOnDoWork(Object sender, DoWorkEventArgs e) in C:\Users\TEMP.SKYLUXBANG\Desktop\RecordingExportExample-master\src\RecordingExportExample\RecordingExportExample\ViewModel\ExportViewModel.cs:line 336"

TargetSite = {ININ.IceLib.QualityManagement.RecordingUriData GetExportUriImpl(System.String, ININ.IceLib.QualityManagement.RecordingMediaType, System.String, Int32)}

Thanks
Rajesh Kumar

**Comment by PrinceNebulon** [comment]
@rajeshskylux Please open a ticket with [ININ Support](https://isupportweb.inin.com) to investigate this issue. We cannot troubleshoot your CIC environment via a Github issue.

**Comment by lkalagotla** [comment]
we are also facing the same issue from last 2 weeks. Could you please explain how could you resolve it.

**Comment by rajeshskylux** [comment]
Hi lkalagotla,
    We have created new CIC dev environment and the same code work for us without any change.

**Comment by lkalagotla** [comment]
Thanks Rajesh. Not sure what's causing this issue. We are still investigating.

**Comment by Imraan7862** [comment]
Hi guys,

I've had a similar issue using Icelib, not sure if you are experiencing the same or a different issue, but the reason I kept getting that error is because the recordingID was being searched for is not longer available... If the recording can not be retrieved from ICBM then the IceLib component will fail.. unfortunately it does not give you the exact issue and always returns users privilege messages
